play.mailer {
  host = "smtp.gmail.com"
  port = 587
  ssl = false
  tls = true
  user = "your-gmail@gmail.com"
  password = "your-16-char-app-password"
  from = "your-gmail@gmail.com"
  mock = false
}